import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header  from './Header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fetching Data',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <main className='container mx-auto pt-20 min-h-screen'>
          {children}
        </main>
      </body>
      <footer className="footer footer-center p-4 bg-base-300 text-base-content">
        <aside>
          <p>Copyright © 2023 - All right reserved by Joe Boadi</p>
        </aside>
      </footer>
    </html>
  )
}
